### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by avirdoz** [Virosa/ETHlargementPill#1]
Hi, and thx for repo. What can cause seg. fault immediately after start of the pill?

`xxx@xxx9:~$sudo ./OhGodAnETHlargementPill-r2`
`+----------------------------------------------------------------------------+`
`|                  OhGodAnETHlargementPill by OhGodACompany                  |`
`|            Public Edition Limited to 1080, 1080 Ti and Titan Xp            |`
`+----------------------------------------------------------------------------+`
`ETHlargement pills are currently being served. Please keep this window open, and we'll continue dosing your cards as needed.`
`Segmentation fault`
`xxx@xxx9:~$ uname -a`
`Linux miner8a 4.18.0-0.bpo.1-amd64 #1 SMP Debian 4.18.6-1~bpo9+1 (2018-09-13) x86_64 GNU/Linux`

Some strace info
http://sprunge.us/e0BU6v

**Comment by ryanmilke** [comment]
Add "iomem=relaxed" to your kernel parameters to fix this. I ran into the same issue on Debian 10, and this took care of it.

**Comment by Unnameless** [comment]
> > Add "iomem=relaxed" to your kernel parameters to fix this. I ran into the same issue on Debian 10, and this took care of it.
> 
> Thank you! It works.

Hi,

Can you please link me to the linux pill binary? I can't find it anywhere...

**Comment by ibmua** [comment]
https://github.com/Virosa/ETHlargementPill/blob/master/OhGodAnETHlargementPill-r2
