### ISSUE TITLE
ETHlargmentPill doesn't work on Titan X (Pascal)?

### ISSUE THREAD

**Issue by benjs2000** [Virosa/ETHlargementPill#2]
Hi,

I know this seems to be completely dead but I was hoping someone could advise?

I've noticed that ETHPill doesn't work with the Titan X (Pascal) even though it has GDDR5X like it's successor, the Titan Xp.

Is there anything I can try doing to get it working?

Thanks!

**Comment by Virosa** [comment]
No it only supported specific device IDs. The project is long dead, was a lot of work and didn't generate revenue.
